-- 1 
Use LMS

-- 2
Select ALUNO.NOME as Aluno, ALUNO.RA, DISCIPLINA.NOME as Disciplina, PROFESSOR.NOME as Professor
From DISCIPLINAOFERTADA
Join PROFESSOR ON DISCIPLINAOFERTADA.IDPROFESSOR = PROFESSOR.ID
Join SOLICITACAOMATRICULA ON DISCIPLINAOFERTADA.ID = SOLICITACAOMATRICULA.IDDOFERTADA
Join ALUNO ON SOLICITACAOMATRICULA.IDALUNO = ALUNO.ID
Join DISCIPLINA ON DISCIPLINAOFERTADA.IDDISCIPLINA = DISCIPLINA.ID;

-- 3
Select DISTINCT DISCIPLINA.NOME From DISCIPLINAOFERTADA
Join DISCIPLINA ON DISCIPLINAOFERTADA.IDDISCIPLINA = DISCIPLINA.ID; 

-- 4
Select ENTREGA.STATUS From DISCIPLINAOFERTADA
Join SOLICITACAOMATRICULA ON DISCIPLINAOFERTADA.ID = SOLICITACAOMATRICULA.IDDOFERTADA
Join ALUNO ON SOLICITACAOMATRICULA.IDALUNO = ALUNO.ID
Join ENTREGA ON ALUNO.ID = ENTREGA.IDALUNO
Where ENTREGA.STATUS != 'ENTREGUE' and ENTREGA.STATUS != 'CORRIGIDO';

-- 5
Select ENTREGA.STATUS From DISCIPLINAOFERTADA
Join SOLICITACAOMATRICULA ON DISCIPLINAOFERTADA.ID = SOLICITACAOMATRICULA.IDDOFERTADA
Join ALUNO ON SOLICITACAOMATRICULA.IDALUNO = ALUNO.ID
Join ENTREGA ON ALUNO.ID = ENTREGA.IDALUNO
Where ENTREGA.STATUS = 'ENTREGUE';

-- 6 
Select * From DISCIPLINAOFERTADA
Where IDPROFESSOR is null

-- 7
Select DISCIPLINA.NOME as Disciplina, count(ALUNO.NOME) as [Quantidade de alunos] From DISCIPLINAOFERTADA
Join SOLICITACAOMATRICULA ON DISCIPLINAOFERTADA.ID = SOLICITACAOMATRICULA.IDDOFERTADA
Join ALUNO ON SOLICITACAOMATRICULA.IDALUNO = ALUNO.ID
Join DISCIPLINA ON DISCIPLINAOFERTADA.IDDISCIPLINA = DISCIPLINA.ID
Group by DISCIPLINA.NOME

-- 8 
Select ALUNO.NOME as Aluno, 
case
when ENTREGA.NOTA is null then 0.00
else ENTREGA.NOTA 
end as Nota
From ENTREGA
Join ALUNO ON ENTREGA.IDALUNO = ALUNO.ID
Order by ALUNO.NOME

